# Generated by Django 4.2.9 on 2024-01-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphapp', '0002_alter_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinglist',
            name='posts',
            field=models.ManyToManyField(to='graphapp.post'),
        ),
    ]
