# Generated by Django 4.2.9 on 2024-01-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphapp', '0002_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(default=2, upload_to='media/images'),
            preserve_default=False,
        ),
    ]
